### ISSUE TITLE
No such file or directory: '/.thumbs/'

### ISSUE THREAD

**Issue by luzi2000** [kluoyun/push_wechat#2]
目前是报这个错误
[eventloop.py:_wrapper()] - Error Running Callback
Traceback (most recent call last):
  File "/home/luzi/moonraker/moonraker/eventloop.py", line 73, in _wrapper
    await ret
  File "/home/luzi/moonraker/moonraker/moonraker.py", line 319, in _process_event
    await asyncio.gather(*coroutines)
  File "/home/luzi/moonraker/moonraker/components/push_wechat.py", line 140, in _status_update
    self._pushState(state=state, filename=filename)
  File "/home/luzi/moonraker/moonraker/components/push_wechat.py", line 336, in _pushState
    files = os.listdir(self.gc_path + "/.thumbs/")
FileNotFoundError: [Errno 2] No such file or directory: '/.thumbs/'
应该怎么处理呢

**Comment by luzi2000** [comment]
我实际是有这个目录的，但不是缺省的

**Comment by kluoyun** [comment]
该路径前面并不是“/”，应该是gcodes目录的路径。gcodes路径是获取的moonraker数据库中的“file_manager.gcode_path”。从你的错误看你应该检测你的moonraker的gcodes目录配置

**Comment by luzi2000** [comment]
我看了下 self.gc_path这个值取成空值了，不太清楚原因是啥，我改成绝对路径再试试

**Comment by luzi2000** [comment]
这步过了，现在是微信ip的问题了，我感觉应该是db.get_item("moonraker", "file_manager.gcode_path", "").result()取值的时候没取的问题，是不是moonraker的版本问题呢

**Comment by kluoyun** [comment]
我看了最新的moonraker，数据库中的键并没有修改，正常是不会空的。有可能是moonraker最近将路径修改为“~/printer_data/”的问题，有时间我在看看

**Comment by kluoyun** [comment]
微信机制修改，现在都必须添加白名单才可以

**Comment by luzi2000** [comment]
可信域名这个有点难度。。。多谢

**Comment by luzi2000** [comment]
我看了下代码，也支持直接发邮件是吧

**Comment by luzi2000** [comment]
好象还没开发完。。。好吧

**Comment by kluoyun** [comment]
这只是周末随便写的。最近工作太忙，没有时间
